const githubUserResponse = r"""
  {
    "login": "fajusto",
    "id": 14909648,
    "node_id": "MDQ6VXNlcjE0OTA5NjQ4",
    "avatar_url": "https://avatars.githubusercontent.com/u/14909648?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fajusto",
    "html_url": "https://github.com/fajusto",
    "followers_url": "https://api.github.com/users/fajusto/followers",
    "following_url": "https://api.github.com/users/fajusto/following{/other_user}",
    "gists_url": "https://api.github.com/users/fajusto/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fajusto/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fajusto/subscriptions",
    "organizations_url": "https://api.github.com/users/fajusto/orgs",
    "repos_url": "https://api.github.com/users/fajusto/repos",
    "events_url": "https://api.github.com/users/fajusto/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fajusto/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Fabrício Justo",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "I’m a self learner, technology lover, and enjoy coding too much.",
    "twitter_username": null,
    "public_repos": 19,
    "public_gists": 0,
    "followers": 3,
    "following": 4,
    "created_at": "2015-09-30T15:48:48Z",
    "updated_at": "2021-09-01T02:49:38Z"
  }
""";