const githubResult = r"""
  {
    "total_count": 4321,
    "incomplete_results": false,
    "items": [
        {
            "login": "fabricio",
            "id": 3382,
            "node_id": "MDQ6VXNlcjMzODI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3382?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabricio",
            "html_url": "https://github.com/fabricio",
            "followers_url": "https://api.github.com/users/fabricio/followers",
            "following_url": "https://api.github.com/users/fabricio/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabricio/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabricio/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabricio/subscriptions",
            "organizations_url": "https://api.github.com/users/fabricio/orgs",
            "repos_url": "https://api.github.com/users/fabricio/repos",
            "events_url": "https://api.github.com/users/fabricio/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabricio/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fczuardi",
            "id": 7760,
            "node_id": "MDQ6VXNlcjc3NjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7760?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fczuardi",
            "html_url": "https://github.com/fczuardi",
            "followers_url": "https://api.github.com/users/fczuardi/followers",
            "following_url": "https://api.github.com/users/fczuardi/following{/other_user}",
            "gists_url": "https://api.github.com/users/fczuardi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fczuardi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fczuardi/subscriptions",
            "organizations_url": "https://api.github.com/users/fczuardi/orgs",
            "repos_url": "https://api.github.com/users/fczuardi/repos",
            "events_url": "https://api.github.com/users/fczuardi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fczuardi/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabricioveronez",
            "id": 854914,
            "node_id": "MDQ6VXNlcjg1NDkxNA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/854914?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabricioveronez",
            "html_url": "https://github.com/fabricioveronez",
            "followers_url": "https://api.github.com/users/fabricioveronez/followers",
            "following_url": "https://api.github.com/users/fabricioveronez/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabricioveronez/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabricioveronez/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabricioveronez/subscriptions",
            "organizations_url": "https://api.github.com/users/fabricioveronez/orgs",
            "repos_url": "https://api.github.com/users/fabricioveronez/repos",
            "events_url": "https://api.github.com/users/fabricioveronez/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabricioveronez/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciomrkonell",
            "id": 4234986,
            "node_id": "MDQ6VXNlcjQyMzQ5ODY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4234986?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciomrkonell",
            "html_url": "https://github.com/fabriciomrkonell",
            "followers_url": "https://api.github.com/users/fabriciomrkonell/followers",
            "following_url": "https://api.github.com/users/fabriciomrkonell/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciomrkonell/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciomrkonell/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciomrkonell/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciomrkonell/orgs",
            "repos_url": "https://api.github.com/users/fabriciomrkonell/repos",
            "events_url": "https://api.github.com/users/fabriciomrkonell/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciomrkonell/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciodorneles",
            "id": 64965851,
            "node_id": "MDQ6VXNlcjY0OTY1ODUx",
            "avatar_url": "https://avatars.githubusercontent.com/u/64965851?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciodorneles",
            "html_url": "https://github.com/fabriciodorneles",
            "followers_url": "https://api.github.com/users/fabriciodorneles/followers",
            "following_url": "https://api.github.com/users/fabriciodorneles/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciodorneles/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciodorneles/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciodorneles/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciodorneles/orgs",
            "repos_url": "https://api.github.com/users/fabriciodorneles/repos",
            "events_url": "https://api.github.com/users/fabriciodorneles/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciodorneles/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciocolombo",
            "id": 842859,
            "node_id": "MDQ6VXNlcjg0Mjg1OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/842859?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciocolombo",
            "html_url": "https://github.com/fabriciocolombo",
            "followers_url": "https://api.github.com/users/fabriciocolombo/followers",
            "following_url": "https://api.github.com/users/fabriciocolombo/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciocolombo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciocolombo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciocolombo/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciocolombo/orgs",
            "repos_url": "https://api.github.com/users/fabriciocolombo/repos",
            "events_url": "https://api.github.com/users/fabriciocolombo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciocolombo/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabricionaweb",
            "id": 15933,
            "node_id": "MDQ6VXNlcjE1OTMz",
            "avatar_url": "https://avatars.githubusercontent.com/u/15933?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabricionaweb",
            "html_url": "https://github.com/fabricionaweb",
            "followers_url": "https://api.github.com/users/fabricionaweb/followers",
            "following_url": "https://api.github.com/users/fabricionaweb/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabricionaweb/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabricionaweb/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabricionaweb/subscriptions",
            "organizations_url": "https://api.github.com/users/fabricionaweb/orgs",
            "repos_url": "https://api.github.com/users/fabricionaweb/repos",
            "events_url": "https://api.github.com/users/fabricionaweb/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabricionaweb/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fpolica91",
            "id": 39638775,
            "node_id": "MDQ6VXNlcjM5NjM4Nzc1",
            "avatar_url": "https://avatars.githubusercontent.com/u/39638775?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fpolica91",
            "html_url": "https://github.com/fpolica91",
            "followers_url": "https://api.github.com/users/fpolica91/followers",
            "following_url": "https://api.github.com/users/fpolica91/following{/other_user}",
            "gists_url": "https://api.github.com/users/fpolica91/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fpolica91/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fpolica91/subscriptions",
            "organizations_url": "https://api.github.com/users/fpolica91/orgs",
            "repos_url": "https://api.github.com/users/fpolica91/repos",
            "events_url": "https://api.github.com/users/fpolica91/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fpolica91/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciofx",
            "id": 1964562,
            "node_id": "MDQ6VXNlcjE5NjQ1NjI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1964562?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciofx",
            "html_url": "https://github.com/fabriciofx",
            "followers_url": "https://api.github.com/users/fabriciofx/followers",
            "following_url": "https://api.github.com/users/fabriciofx/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciofx/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciofx/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciofx/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciofx/orgs",
            "repos_url": "https://api.github.com/users/fabriciofx/repos",
            "events_url": "https://api.github.com/users/fabriciofx/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciofx/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "FabricioFFC",
            "id": 139354,
            "node_id": "MDQ6VXNlcjEzOTM1NA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/139354?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/FabricioFFC",
            "html_url": "https://github.com/FabricioFFC",
            "followers_url": "https://api.github.com/users/FabricioFFC/followers",
            "following_url": "https://api.github.com/users/FabricioFFC/following{/other_user}",
            "gists_url": "https://api.github.com/users/FabricioFFC/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/FabricioFFC/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FabricioFFC/subscriptions",
            "organizations_url": "https://api.github.com/users/FabricioFFC/orgs",
            "repos_url": "https://api.github.com/users/FabricioFFC/repos",
            "events_url": "https://api.github.com/users/FabricioFFC/events{/privacy}",
            "received_events_url": "https://api.github.com/users/FabricioFFC/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "Ernakh",
            "id": 3999201,
            "node_id": "MDQ6VXNlcjM5OTkyMDE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3999201?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Ernakh",
            "html_url": "https://github.com/Ernakh",
            "followers_url": "https://api.github.com/users/Ernakh/followers",
            "following_url": "https://api.github.com/users/Ernakh/following{/other_user}",
            "gists_url": "https://api.github.com/users/Ernakh/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Ernakh/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Ernakh/subscriptions",
            "organizations_url": "https://api.github.com/users/Ernakh/orgs",
            "repos_url": "https://api.github.com/users/Ernakh/repos",
            "events_url": "https://api.github.com/users/Ernakh/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Ernakh/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciocovalesci",
            "id": 40548641,
            "node_id": "MDQ6VXNlcjQwNTQ4NjQx",
            "avatar_url": "https://avatars.githubusercontent.com/u/40548641?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciocovalesci",
            "html_url": "https://github.com/fabriciocovalesci",
            "followers_url": "https://api.github.com/users/fabriciocovalesci/followers",
            "following_url": "https://api.github.com/users/fabriciocovalesci/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciocovalesci/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciocovalesci/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciocovalesci/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciocovalesci/orgs",
            "repos_url": "https://api.github.com/users/fabriciocovalesci/repos",
            "events_url": "https://api.github.com/users/fabriciocovalesci/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciocovalesci/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciorissetto",
            "id": 1520059,
            "node_id": "MDQ6VXNlcjE1MjAwNTk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1520059?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciorissetto",
            "html_url": "https://github.com/fabriciorissetto",
            "followers_url": "https://api.github.com/users/fabriciorissetto/followers",
            "following_url": "https://api.github.com/users/fabriciorissetto/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciorissetto/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciorissetto/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciorissetto/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciorissetto/orgs",
            "repos_url": "https://api.github.com/users/fabriciorissetto/repos",
            "events_url": "https://api.github.com/users/fabriciorissetto/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciorissetto/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciojs",
            "id": 1116377,
            "node_id": "MDQ6VXNlcjExMTYzNzc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1116377?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciojs",
            "html_url": "https://github.com/fabriciojs",
            "followers_url": "https://api.github.com/users/fabriciojs/followers",
            "following_url": "https://api.github.com/users/fabriciojs/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciojs/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciojs/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciojs/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciojs/orgs",
            "repos_url": "https://api.github.com/users/fabriciojs/repos",
            "events_url": "https://api.github.com/users/fabriciojs/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciojs/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciofmsilva",
            "id": 3485525,
            "node_id": "MDQ6VXNlcjM0ODU1MjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3485525?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciofmsilva",
            "html_url": "https://github.com/fabriciofmsilva",
            "followers_url": "https://api.github.com/users/fabriciofmsilva/followers",
            "following_url": "https://api.github.com/users/fabriciofmsilva/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciofmsilva/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciofmsilva/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciofmsilva/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciofmsilva/orgs",
            "repos_url": "https://api.github.com/users/fabriciofmsilva/repos",
            "events_url": "https://api.github.com/users/fabriciofmsilva/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciofmsilva/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "Fabricio20",
            "id": 7545720,
            "node_id": "MDQ6VXNlcjc1NDU3MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7545720?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Fabricio20",
            "html_url": "https://github.com/Fabricio20",
            "followers_url": "https://api.github.com/users/Fabricio20/followers",
            "following_url": "https://api.github.com/users/Fabricio20/following{/other_user}",
            "gists_url": "https://api.github.com/users/Fabricio20/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Fabricio20/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Fabricio20/subscriptions",
            "organizations_url": "https://api.github.com/users/Fabricio20/orgs",
            "repos_url": "https://api.github.com/users/Fabricio20/repos",
            "events_url": "https://api.github.com/users/Fabricio20/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Fabricio20/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciobedin",
            "id": 18118086,
            "node_id": "MDQ6VXNlcjE4MTE4MDg2",
            "avatar_url": "https://avatars.githubusercontent.com/u/18118086?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciobedin",
            "html_url": "https://github.com/fabriciobedin",
            "followers_url": "https://api.github.com/users/fabriciobedin/followers",
            "following_url": "https://api.github.com/users/fabriciobedin/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciobedin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciobedin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciobedin/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciobedin/orgs",
            "repos_url": "https://api.github.com/users/fabriciobedin/repos",
            "events_url": "https://api.github.com/users/fabriciobedin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciobedin/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fao89",
            "id": 17153022,
            "node_id": "MDQ6VXNlcjE3MTUzMDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/17153022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fao89",
            "html_url": "https://github.com/fao89",
            "followers_url": "https://api.github.com/users/fao89/followers",
            "following_url": "https://api.github.com/users/fao89/following{/other_user}",
            "gists_url": "https://api.github.com/users/fao89/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fao89/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fao89/subscriptions",
            "organizations_url": "https://api.github.com/users/fao89/orgs",
            "repos_url": "https://api.github.com/users/fao89/repos",
            "events_url": "https://api.github.com/users/fao89/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fao89/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fcatae",
            "id": 7252609,
            "node_id": "MDQ6VXNlcjcyNTI2MDk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7252609?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fcatae",
            "html_url": "https://github.com/fcatae",
            "followers_url": "https://api.github.com/users/fcatae/followers",
            "following_url": "https://api.github.com/users/fcatae/following{/other_user}",
            "gists_url": "https://api.github.com/users/fcatae/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fcatae/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fcatae/subscriptions",
            "organizations_url": "https://api.github.com/users/fcatae/orgs",
            "repos_url": "https://api.github.com/users/fcatae/repos",
            "events_url": "https://api.github.com/users/fcatae/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fcatae/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciotuosto",
            "id": 166186,
            "node_id": "MDQ6VXNlcjE2NjE4Ng==",
            "avatar_url": "https://avatars.githubusercontent.com/u/166186?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciotuosto",
            "html_url": "https://github.com/fabriciotuosto",
            "followers_url": "https://api.github.com/users/fabriciotuosto/followers",
            "following_url": "https://api.github.com/users/fabriciotuosto/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciotuosto/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciotuosto/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciotuosto/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciotuosto/orgs",
            "repos_url": "https://api.github.com/users/fabriciotuosto/repos",
            "events_url": "https://api.github.com/users/fabriciotuosto/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciotuosto/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciosanchez",
            "id": 1838729,
            "node_id": "MDQ6VXNlcjE4Mzg3Mjk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1838729?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciosanchez",
            "html_url": "https://github.com/fabriciosanchez",
            "followers_url": "https://api.github.com/users/fabriciosanchez/followers",
            "following_url": "https://api.github.com/users/fabriciosanchez/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciosanchez/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciosanchez/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciosanchez/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciosanchez/orgs",
            "repos_url": "https://api.github.com/users/fabriciosanchez/repos",
            "events_url": "https://api.github.com/users/fabriciosanchez/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciosanchez/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabricioromanii",
            "id": 50345597,
            "node_id": "MDQ6VXNlcjUwMzQ1NTk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/50345597?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabricioromanii",
            "html_url": "https://github.com/fabricioromanii",
            "followers_url": "https://api.github.com/users/fabricioromanii/followers",
            "following_url": "https://api.github.com/users/fabricioromanii/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabricioromanii/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabricioromanii/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabricioromanii/subscriptions",
            "organizations_url": "https://api.github.com/users/fabricioromanii/orgs",
            "repos_url": "https://api.github.com/users/fabricioromanii/repos",
            "events_url": "https://api.github.com/users/fabricioromanii/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabricioromanii/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciocunhauk",
            "id": 60474481,
            "node_id": "MDQ6VXNlcjYwNDc0NDgx",
            "avatar_url": "https://avatars.githubusercontent.com/u/60474481?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciocunhauk",
            "html_url": "https://github.com/fabriciocunhauk",
            "followers_url": "https://api.github.com/users/fabriciocunhauk/followers",
            "following_url": "https://api.github.com/users/fabriciocunhauk/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciocunhauk/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciocunhauk/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciocunhauk/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciocunhauk/orgs",
            "repos_url": "https://api.github.com/users/fabriciocunhauk/repos",
            "events_url": "https://api.github.com/users/fabriciocunhauk/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciocunhauk/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "Fziliotti",
            "id": 28535210,
            "node_id": "MDQ6VXNlcjI4NTM1MjEw",
            "avatar_url": "https://avatars.githubusercontent.com/u/28535210?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Fziliotti",
            "html_url": "https://github.com/Fziliotti",
            "followers_url": "https://api.github.com/users/Fziliotti/followers",
            "following_url": "https://api.github.com/users/Fziliotti/following{/other_user}",
            "gists_url": "https://api.github.com/users/Fziliotti/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Fziliotti/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Fziliotti/subscriptions",
            "organizations_url": "https://api.github.com/users/Fziliotti/orgs",
            "repos_url": "https://api.github.com/users/Fziliotti/repos",
            "events_url": "https://api.github.com/users/Fziliotti/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Fziliotti/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciolfj",
            "id": 62782102,
            "node_id": "MDQ6VXNlcjYyNzgyMTAy",
            "avatar_url": "https://avatars.githubusercontent.com/u/62782102?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciolfj",
            "html_url": "https://github.com/fabriciolfj",
            "followers_url": "https://api.github.com/users/fabriciolfj/followers",
            "following_url": "https://api.github.com/users/fabriciolfj/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciolfj/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciolfj/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciolfj/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciolfj/orgs",
            "repos_url": "https://api.github.com/users/fabriciolfj/repos",
            "events_url": "https://api.github.com/users/fabriciolfj/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciolfj/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciosaand",
            "id": 219049,
            "node_id": "MDQ6VXNlcjIxOTA0OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/219049?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciosaand",
            "html_url": "https://github.com/fabriciosaand",
            "followers_url": "https://api.github.com/users/fabriciosaand/followers",
            "following_url": "https://api.github.com/users/fabriciosaand/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciosaand/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciosaand/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciosaand/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciosaand/orgs",
            "repos_url": "https://api.github.com/users/fabriciosaand/repos",
            "events_url": "https://api.github.com/users/fabriciosaand/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciosaand/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "FabricioLiber",
            "id": 22638603,
            "node_id": "MDQ6VXNlcjIyNjM4NjAz",
            "avatar_url": "https://avatars.githubusercontent.com/u/22638603?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/FabricioLiber",
            "html_url": "https://github.com/FabricioLiber",
            "followers_url": "https://api.github.com/users/FabricioLiber/followers",
            "following_url": "https://api.github.com/users/FabricioLiber/following{/other_user}",
            "gists_url": "https://api.github.com/users/FabricioLiber/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/FabricioLiber/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FabricioLiber/subscriptions",
            "organizations_url": "https://api.github.com/users/FabricioLiber/orgs",
            "repos_url": "https://api.github.com/users/FabricioLiber/repos",
            "events_url": "https://api.github.com/users/FabricioLiber/events{/privacy}",
            "received_events_url": "https://api.github.com/users/FabricioLiber/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "UltCombo",
            "id": 2090712,
            "node_id": "MDQ6VXNlcjIwOTA3MTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2090712?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/UltCombo",
            "html_url": "https://github.com/UltCombo",
            "followers_url": "https://api.github.com/users/UltCombo/followers",
            "following_url": "https://api.github.com/users/UltCombo/following{/other_user}",
            "gists_url": "https://api.github.com/users/UltCombo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/UltCombo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/UltCombo/subscriptions",
            "organizations_url": "https://api.github.com/users/UltCombo/orgs",
            "repos_url": "https://api.github.com/users/UltCombo/repos",
            "events_url": "https://api.github.com/users/UltCombo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/UltCombo/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "baricio",
            "id": 1015059,
            "node_id": "MDQ6VXNlcjEwMTUwNTk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1015059?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/baricio",
            "html_url": "https://github.com/baricio",
            "followers_url": "https://api.github.com/users/baricio/followers",
            "following_url": "https://api.github.com/users/baricio/following{/other_user}",
            "gists_url": "https://api.github.com/users/baricio/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/baricio/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/baricio/subscriptions",
            "organizations_url": "https://api.github.com/users/baricio/orgs",
            "repos_url": "https://api.github.com/users/baricio/repos",
            "events_url": "https://api.github.com/users/baricio/events{/privacy}",
            "received_events_url": "https://api.github.com/users/baricio/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "fabriciomsdev",
            "id": 48806218,
            "node_id": "MDQ6VXNlcjQ4ODA2MjE4",
            "avatar_url": "https://avatars.githubusercontent.com/u/48806218?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabriciomsdev",
            "html_url": "https://github.com/fabriciomsdev",
            "followers_url": "https://api.github.com/users/fabriciomsdev/followers",
            "following_url": "https://api.github.com/users/fabriciomsdev/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabriciomsdev/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabriciomsdev/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabriciomsdev/subscriptions",
            "organizations_url": "https://api.github.com/users/fabriciomsdev/orgs",
            "repos_url": "https://api.github.com/users/fabriciomsdev/repos",
            "events_url": "https://api.github.com/users/fabriciomsdev/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabriciomsdev/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1
        }
    ]
  }
""";
