const githubResult = """ 
{
  "total_count": 11,
  "incomplete_results": false,
  "items": [
    {
      "login": "ivanaldo",
      "id": 44933707,
      "node_id": "MDQ6VXNlcjQ0OTMzNzA3",
      "avatar_url": "https://avatars.githubusercontent.com/u/44933707?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanaldo",
      "html_url": "https://github.com/ivanaldo",
      "followers_url": "https://api.github.com/users/ivanaldo/followers",
      "following_url": "https://api.github.com/users/ivanaldo/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanaldo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanaldo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanaldo/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanaldo/orgs",
      "repos_url": "https://api.github.com/users/ivanaldo/repos",
      "events_url": "https://api.github.com/users/ivanaldo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanaldo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "IVANALDOSANTOS",
      "id": 62851597,
      "node_id": "MDQ6VXNlcjYyODUxNTk3",
      "avatar_url": "https://avatars.githubusercontent.com/u/62851597?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/IVANALDOSANTOS",
      "html_url": "https://github.com/IVANALDOSANTOS",
      "followers_url": "https://api.github.com/users/IVANALDOSANTOS/followers",
      "following_url": "https://api.github.com/users/IVANALDOSANTOS/following{/other_user}",
      "gists_url": "https://api.github.com/users/IVANALDOSANTOS/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/IVANALDOSANTOS/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/IVANALDOSANTOS/subscriptions",
      "organizations_url": "https://api.github.com/users/IVANALDOSANTOS/orgs",
      "repos_url": "https://api.github.com/users/IVANALDOSANTOS/repos",
      "events_url": "https://api.github.com/users/IVANALDOSANTOS/events{/privacy}",
      "received_events_url": "https://api.github.com/users/IVANALDOSANTOS/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ryanivanaldo",
      "id": 23162425,
      "node_id": "MDQ6VXNlcjIzMTYyNDI1",
      "avatar_url": "https://avatars.githubusercontent.com/u/23162425?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ryanivanaldo",
      "html_url": "https://github.com/ryanivanaldo",
      "followers_url": "https://api.github.com/users/ryanivanaldo/followers",
      "following_url": "https://api.github.com/users/ryanivanaldo/following{/other_user}",
      "gists_url": "https://api.github.com/users/ryanivanaldo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ryanivanaldo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ryanivanaldo/subscriptions",
      "organizations_url": "https://api.github.com/users/ryanivanaldo/orgs",
      "repos_url": "https://api.github.com/users/ryanivanaldo/repos",
      "events_url": "https://api.github.com/users/ryanivanaldo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ryanivanaldo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Ivanaldotj",
      "id": 37883483,
      "node_id": "MDQ6VXNlcjM3ODgzNDgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/37883483?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ivanaldotj",
      "html_url": "https://github.com/Ivanaldotj",
      "followers_url": "https://api.github.com/users/Ivanaldotj/followers",
      "following_url": "https://api.github.com/users/Ivanaldotj/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ivanaldotj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ivanaldotj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ivanaldotj/subscriptions",
      "organizations_url": "https://api.github.com/users/Ivanaldotj/orgs",
      "repos_url": "https://api.github.com/users/Ivanaldotj/repos",
      "events_url": "https://api.github.com/users/Ivanaldotj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ivanaldotj/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ivanaldo79",
      "id": 54161887,
      "node_id": "MDQ6VXNlcjU0MTYxODg3",
      "avatar_url": "https://avatars.githubusercontent.com/u/54161887?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanaldo79",
      "html_url": "https://github.com/ivanaldo79",
      "followers_url": "https://api.github.com/users/ivanaldo79/followers",
      "following_url": "https://api.github.com/users/ivanaldo79/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanaldo79/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanaldo79/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanaldo79/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanaldo79/orgs",
      "repos_url": "https://api.github.com/users/ivanaldo79/repos",
      "events_url": "https://api.github.com/users/ivanaldo79/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanaldo79/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "IvanaldoJunior",
      "id": 59888269,
      "node_id": "MDQ6VXNlcjU5ODg4MjY5",
      "avatar_url": "https://avatars.githubusercontent.com/u/59888269?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/IvanaldoJunior",
      "html_url": "https://github.com/IvanaldoJunior",
      "followers_url": "https://api.github.com/users/IvanaldoJunior/followers",
      "following_url": "https://api.github.com/users/IvanaldoJunior/following{/other_user}",
      "gists_url": "https://api.github.com/users/IvanaldoJunior/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/IvanaldoJunior/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/IvanaldoJunior/subscriptions",
      "organizations_url": "https://api.github.com/users/IvanaldoJunior/orgs",
      "repos_url": "https://api.github.com/users/IvanaldoJunior/repos",
      "events_url": "https://api.github.com/users/IvanaldoJunior/events{/privacy}",
      "received_events_url": "https://api.github.com/users/IvanaldoJunior/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "IvanaldoCosta",
      "id": 12720772,
      "node_id": "MDQ6VXNlcjEyNzIwNzcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/12720772?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/IvanaldoCosta",
      "html_url": "https://github.com/IvanaldoCosta",
      "followers_url": "https://api.github.com/users/IvanaldoCosta/followers",
      "following_url": "https://api.github.com/users/IvanaldoCosta/following{/other_user}",
      "gists_url": "https://api.github.com/users/IvanaldoCosta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/IvanaldoCosta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/IvanaldoCosta/subscriptions",
      "organizations_url": "https://api.github.com/users/IvanaldoCosta/orgs",
      "repos_url": "https://api.github.com/users/IvanaldoCosta/repos",
      "events_url": "https://api.github.com/users/IvanaldoCosta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/IvanaldoCosta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ivanaldo10",
      "id": 39860673,
      "node_id": "MDQ6VXNlcjM5ODYwNjcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/39860673?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanaldo10",
      "html_url": "https://github.com/ivanaldo10",
      "followers_url": "https://api.github.com/users/ivanaldo10/followers",
      "following_url": "https://api.github.com/users/ivanaldo10/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanaldo10/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanaldo10/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanaldo10/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanaldo10/orgs",
      "repos_url": "https://api.github.com/users/ivanaldo10/repos",
      "events_url": "https://api.github.com/users/ivanaldo10/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanaldo10/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ivanaldofr",
      "id": 58347617,
      "node_id": "MDQ6VXNlcjU4MzQ3NjE3",
      "avatar_url": "https://avatars.githubusercontent.com/u/58347617?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanaldofr",
      "html_url": "https://github.com/ivanaldofr",
      "followers_url": "https://api.github.com/users/ivanaldofr/followers",
      "following_url": "https://api.github.com/users/ivanaldofr/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanaldofr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanaldofr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanaldofr/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanaldofr/orgs",
      "repos_url": "https://api.github.com/users/ivanaldofr/repos",
      "events_url": "https://api.github.com/users/ivanaldofr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanaldofr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ivanaldo311",
      "id": 66676434,
      "node_id": "MDQ6VXNlcjY2Njc2NDM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/66676434?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanaldo311",
      "html_url": "https://github.com/ivanaldo311",
      "followers_url": "https://api.github.com/users/ivanaldo311/followers",
      "following_url": "https://api.github.com/users/ivanaldo311/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanaldo311/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanaldo311/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanaldo311/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanaldo311/orgs",
      "repos_url": "https://api.github.com/users/ivanaldo311/repos",
      "events_url": "https://api.github.com/users/ivanaldo311/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanaldo311/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ivanaldocorreia",
      "id": 81370319,
      "node_id": "MDQ6VXNlcjgxMzcwMzE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/81370319?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanaldocorreia",
      "html_url": "https://github.com/ivanaldocorreia",
      "followers_url": "https://api.github.com/users/ivanaldocorreia/followers",
      "following_url": "https://api.github.com/users/ivanaldocorreia/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanaldocorreia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanaldocorreia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanaldocorreia/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanaldocorreia/orgs",
      "repos_url": "https://api.github.com/users/ivanaldocorreia/repos",
      "events_url": "https://api.github.com/users/ivanaldocorreia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanaldocorreia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";