
const githubResult = """
{
  "total_count": 38,
  "incomplete_results": false,
  "items": [
    {
      "login": "shirlei",
      "id": 234995,
      "node_id": "MDQ6VXNlcjIzNDk5NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/234995?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirlei",
      "html_url": "https://github.com/shirlei",
      "followers_url": "https://api.github.com/users/shirlei/followers",
      "following_url": "https://api.github.com/users/shirlei/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirlei/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirlei/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirlei/subscriptions",
      "organizations_url": "https://api.github.com/users/shirlei/orgs",
      "repos_url": "https://api.github.com/users/shirlei/repos",
      "events_url": "https://api.github.com/users/shirlei/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirlei/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ShirleiMachado",
      "id": 62224847,
      "node_id": "MDQ6VXNlcjYyMjI0ODQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/62224847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ShirleiMachado",
      "html_url": "https://github.com/ShirleiMachado",
      "followers_url": "https://api.github.com/users/ShirleiMachado/followers",
      "following_url": "https://api.github.com/users/ShirleiMachado/following{/other_user}",
      "gists_url": "https://api.github.com/users/ShirleiMachado/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ShirleiMachado/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ShirleiMachado/subscriptions",
      "organizations_url": "https://api.github.com/users/ShirleiMachado/orgs",
      "repos_url": "https://api.github.com/users/ShirleiMachado/repos",
      "events_url": "https://api.github.com/users/ShirleiMachado/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ShirleiMachado/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleide",
      "id": 40605122,
      "node_id": "MDQ6VXNlcjQwNjA1MTIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/40605122?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleide",
      "html_url": "https://github.com/shirleide",
      "followers_url": "https://api.github.com/users/shirleide/followers",
      "following_url": "https://api.github.com/users/shirleide/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleide/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleide/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleide/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleide/orgs",
      "repos_url": "https://api.github.com/users/shirleide/repos",
      "events_url": "https://api.github.com/users/shirleide/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleide/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ShirleiRSC",
      "id": 17753056,
      "node_id": "MDQ6VXNlcjE3NzUzMDU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/17753056?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ShirleiRSC",
      "html_url": "https://github.com/ShirleiRSC",
      "followers_url": "https://api.github.com/users/ShirleiRSC/followers",
      "following_url": "https://api.github.com/users/ShirleiRSC/following{/other_user}",
      "gists_url": "https://api.github.com/users/ShirleiRSC/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ShirleiRSC/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ShirleiRSC/subscriptions",
      "organizations_url": "https://api.github.com/users/ShirleiRSC/orgs",
      "repos_url": "https://api.github.com/users/ShirleiRSC/repos",
      "events_url": "https://api.github.com/users/ShirleiRSC/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ShirleiRSC/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shluh",
      "id": 5185842,
      "node_id": "MDQ6VXNlcjUxODU4NDI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5185842?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shluh",
      "html_url": "https://github.com/shluh",
      "followers_url": "https://api.github.com/users/shluh/followers",
      "following_url": "https://api.github.com/users/shluh/following{/other_user}",
      "gists_url": "https://api.github.com/users/shluh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shluh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shluh/subscriptions",
      "organizations_url": "https://api.github.com/users/shluh/orgs",
      "repos_url": "https://api.github.com/users/shluh/repos",
      "events_url": "https://api.github.com/users/shluh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shluh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ShirleiValim",
      "id": 81879626,
      "node_id": "MDQ6VXNlcjgxODc5NjI2",
      "avatar_url": "https://avatars.githubusercontent.com/u/81879626?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ShirleiValim",
      "html_url": "https://github.com/ShirleiValim",
      "followers_url": "https://api.github.com/users/ShirleiValim/followers",
      "following_url": "https://api.github.com/users/ShirleiValim/following{/other_user}",
      "gists_url": "https://api.github.com/users/ShirleiValim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ShirleiValim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ShirleiValim/subscriptions",
      "organizations_url": "https://api.github.com/users/ShirleiValim/orgs",
      "repos_url": "https://api.github.com/users/ShirleiValim/repos",
      "events_url": "https://api.github.com/users/ShirleiValim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ShirleiValim/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ShirLeizerman",
      "id": 32272872,
      "node_id": "MDQ6VXNlcjMyMjcyODcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/32272872?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ShirLeizerman",
      "html_url": "https://github.com/ShirLeizerman",
      "followers_url": "https://api.github.com/users/ShirLeizerman/followers",
      "following_url": "https://api.github.com/users/ShirLeizerman/following{/other_user}",
      "gists_url": "https://api.github.com/users/ShirLeizerman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ShirLeizerman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ShirLeizerman/subscriptions",
      "organizations_url": "https://api.github.com/users/ShirLeizerman/orgs",
      "repos_url": "https://api.github.com/users/ShirLeizerman/repos",
      "events_url": "https://api.github.com/users/ShirLeizerman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ShirLeizerman/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shurly",
      "id": 40645254,
      "node_id": "MDQ6VXNlcjQwNjQ1MjU0",
      "avatar_url": "https://avatars.githubusercontent.com/u/40645254?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shurly",
      "html_url": "https://github.com/shurly",
      "followers_url": "https://api.github.com/users/shurly/followers",
      "following_url": "https://api.github.com/users/shurly/following{/other_user}",
      "gists_url": "https://api.github.com/users/shurly/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shurly/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shurly/subscriptions",
      "organizations_url": "https://api.github.com/users/shurly/orgs",
      "repos_url": "https://api.github.com/users/shurly/repos",
      "events_url": "https://api.github.com/users/shurly/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shurly/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleimn",
      "id": 67120682,
      "node_id": "MDQ6VXNlcjY3MTIwNjgy",
      "avatar_url": "https://avatars.githubusercontent.com/u/67120682?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleimn",
      "html_url": "https://github.com/shirleimn",
      "followers_url": "https://api.github.com/users/shirleimn/followers",
      "following_url": "https://api.github.com/users/shirleimn/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleimn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleimn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleimn/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleimn/orgs",
      "repos_url": "https://api.github.com/users/shirleimn/repos",
      "events_url": "https://api.github.com/users/shirleimn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleimn/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleias",
      "id": 68550342,
      "node_id": "MDQ6VXNlcjY4NTUwMzQy",
      "avatar_url": "https://avatars.githubusercontent.com/u/68550342?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleias",
      "html_url": "https://github.com/shirleias",
      "followers_url": "https://api.github.com/users/shirleias/followers",
      "following_url": "https://api.github.com/users/shirleias/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleias/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleias/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleias/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleias/orgs",
      "repos_url": "https://api.github.com/users/shirleias/repos",
      "events_url": "https://api.github.com/users/shirleias/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleias/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirlei1408",
      "id": 51887194,
      "node_id": "MDQ6VXNlcjUxODg3MTk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/51887194?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirlei1408",
      "html_url": "https://github.com/shirlei1408",
      "followers_url": "https://api.github.com/users/shirlei1408/followers",
      "following_url": "https://api.github.com/users/shirlei1408/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirlei1408/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirlei1408/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirlei1408/subscriptions",
      "organizations_url": "https://api.github.com/users/shirlei1408/orgs",
      "repos_url": "https://api.github.com/users/shirlei1408/repos",
      "events_url": "https://api.github.com/users/shirlei1408/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirlei1408/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleia",
      "id": 39699338,
      "node_id": "MDQ6VXNlcjM5Njk5MzM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/39699338?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleia",
      "html_url": "https://github.com/shirleia",
      "followers_url": "https://api.github.com/users/shirleia/followers",
      "following_url": "https://api.github.com/users/shirleia/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleia/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleia/orgs",
      "repos_url": "https://api.github.com/users/shirleia/repos",
      "events_url": "https://api.github.com/users/shirleia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleisousa",
      "id": 64554316,
      "node_id": "MDQ6VXNlcjY0NTU0MzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/64554316?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleisousa",
      "html_url": "https://github.com/shirleisousa",
      "followers_url": "https://api.github.com/users/shirleisousa/followers",
      "following_url": "https://api.github.com/users/shirleisousa/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleisousa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleisousa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleisousa/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleisousa/orgs",
      "repos_url": "https://api.github.com/users/shirleisousa/repos",
      "events_url": "https://api.github.com/users/shirleisousa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleisousa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleipatricia",
      "id": 59085423,
      "node_id": "MDQ6VXNlcjU5MDg1NDIz",
      "avatar_url": "https://avatars.githubusercontent.com/u/59085423?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleipatricia",
      "html_url": "https://github.com/shirleipatricia",
      "followers_url": "https://api.github.com/users/shirleipatricia/followers",
      "following_url": "https://api.github.com/users/shirleipatricia/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleipatricia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleipatricia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleipatricia/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleipatricia/orgs",
      "repos_url": "https://api.github.com/users/shirleipatricia/repos",
      "events_url": "https://api.github.com/users/shirleipatricia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleipatricia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Shirlei1975",
      "id": 33843252,
      "node_id": "MDQ6VXNlcjMzODQzMjUy",
      "avatar_url": "https://avatars.githubusercontent.com/u/33843252?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Shirlei1975",
      "html_url": "https://github.com/Shirlei1975",
      "followers_url": "https://api.github.com/users/Shirlei1975/followers",
      "following_url": "https://api.github.com/users/Shirlei1975/following{/other_user}",
      "gists_url": "https://api.github.com/users/Shirlei1975/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Shirlei1975/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Shirlei1975/subscriptions",
      "organizations_url": "https://api.github.com/users/Shirlei1975/orgs",
      "repos_url": "https://api.github.com/users/Shirlei1975/repos",
      "events_url": "https://api.github.com/users/Shirlei1975/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Shirlei1975/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Shirlei1113",
      "id": 38036166,
      "node_id": "MDQ6VXNlcjM4MDM2MTY2",
      "avatar_url": "https://avatars.githubusercontent.com/u/38036166?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Shirlei1113",
      "html_url": "https://github.com/Shirlei1113",
      "followers_url": "https://api.github.com/users/Shirlei1113/followers",
      "following_url": "https://api.github.com/users/Shirlei1113/following{/other_user}",
      "gists_url": "https://api.github.com/users/Shirlei1113/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Shirlei1113/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Shirlei1113/subscriptions",
      "organizations_url": "https://api.github.com/users/Shirlei1113/orgs",
      "repos_url": "https://api.github.com/users/Shirlei1113/repos",
      "events_url": "https://api.github.com/users/Shirlei1113/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Shirlei1113/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleigrey20",
      "id": 67341719,
      "node_id": "MDQ6VXNlcjY3MzQxNzE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/67341719?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleigrey20",
      "html_url": "https://github.com/shirleigrey20",
      "followers_url": "https://api.github.com/users/shirleigrey20/followers",
      "following_url": "https://api.github.com/users/shirleigrey20/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleigrey20/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleigrey20/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleigrey20/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleigrey20/orgs",
      "repos_url": "https://api.github.com/users/shirleigrey20/repos",
      "events_url": "https://api.github.com/users/shirleigrey20/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleigrey20/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleidesousa",
      "id": 60481489,
      "node_id": "MDQ6VXNlcjYwNDgxNDg5",
      "avatar_url": "https://avatars.githubusercontent.com/u/60481489?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleidesousa",
      "html_url": "https://github.com/shirleidesousa",
      "followers_url": "https://api.github.com/users/shirleidesousa/followers",
      "following_url": "https://api.github.com/users/shirleidesousa/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleidesousa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleidesousa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleidesousa/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleidesousa/orgs",
      "repos_url": "https://api.github.com/users/shirleidesousa/repos",
      "events_url": "https://api.github.com/users/shirleidesousa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleidesousa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleialmeida",
      "id": 30410302,
      "node_id": "MDQ6VXNlcjMwNDEwMzAy",
      "avatar_url": "https://avatars.githubusercontent.com/u/30410302?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleialmeida",
      "html_url": "https://github.com/shirleialmeida",
      "followers_url": "https://api.github.com/users/shirleialmeida/followers",
      "following_url": "https://api.github.com/users/shirleialmeida/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleialmeida/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleialmeida/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleialmeida/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleialmeida/orgs",
      "repos_url": "https://api.github.com/users/shirleialmeida/repos",
      "events_url": "https://api.github.com/users/shirleialmeida/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleialmeida/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleiromero",
      "id": 65257104,
      "node_id": "MDQ6VXNlcjY1MjU3MTA0",
      "avatar_url": "https://avatars.githubusercontent.com/u/65257104?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleiromero",
      "html_url": "https://github.com/shirleiromero",
      "followers_url": "https://api.github.com/users/shirleiromero/followers",
      "following_url": "https://api.github.com/users/shirleiromero/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleiromero/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleiromero/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleiromero/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleiromero/orgs",
      "repos_url": "https://api.github.com/users/shirleiromero/repos",
      "events_url": "https://api.github.com/users/shirleiromero/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleiromero/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleibovitch",
      "id": 19950550,
      "node_id": "MDQ6VXNlcjE5OTUwNTUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/19950550?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleibovitch",
      "html_url": "https://github.com/shirleibovitch",
      "followers_url": "https://api.github.com/users/shirleibovitch/followers",
      "following_url": "https://api.github.com/users/shirleibovitch/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleibovitch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleibovitch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleibovitch/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleibovitch/orgs",
      "repos_url": "https://api.github.com/users/shirleibovitch/repos",
      "events_url": "https://api.github.com/users/shirleibovitch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleibovitch/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Shirleihenrique",
      "id": 1083777,
      "node_id": "MDQ6VXNlcjEwODM3Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1083777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Shirleihenrique",
      "html_url": "https://github.com/Shirleihenrique",
      "followers_url": "https://api.github.com/users/Shirleihenrique/followers",
      "following_url": "https://api.github.com/users/Shirleihenrique/following{/other_user}",
      "gists_url": "https://api.github.com/users/Shirleihenrique/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Shirleihenrique/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Shirleihenrique/subscriptions",
      "organizations_url": "https://api.github.com/users/Shirleihenrique/orgs",
      "repos_url": "https://api.github.com/users/Shirleihenrique/repos",
      "events_url": "https://api.github.com/users/Shirleihenrique/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Shirleihenrique/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleiz",
      "id": 8341828,
      "node_id": "MDQ6VXNlcjgzNDE4Mjg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8341828?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleiz",
      "html_url": "https://github.com/shirleiz",
      "followers_url": "https://api.github.com/users/shirleiz/followers",
      "following_url": "https://api.github.com/users/shirleiz/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleiz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleiz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleiz/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleiz/orgs",
      "repos_url": "https://api.github.com/users/shirleiz/repos",
      "events_url": "https://api.github.com/users/shirleiz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleiz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirlei-de-fatima-oliveira",
      "id": 51887244,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjUxODg3MjQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/51887244?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirlei-de-fatima-oliveira",
      "html_url": "https://github.com/shirlei-de-fatima-oliveira",
      "followers_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/followers",
      "following_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/subscriptions",
      "organizations_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/orgs",
      "repos_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/repos",
      "events_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirlei-de-fatima-oliveira/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleiso28",
      "id": 73672888,
      "node_id": "MDQ6VXNlcjczNjcyODg4",
      "avatar_url": "https://avatars.githubusercontent.com/u/73672888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleiso28",
      "html_url": "https://github.com/shirleiso28",
      "followers_url": "https://api.github.com/users/shirleiso28/followers",
      "following_url": "https://api.github.com/users/shirleiso28/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleiso28/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleiso28/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleiso28/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleiso28/orgs",
      "repos_url": "https://api.github.com/users/shirleiso28/repos",
      "events_url": "https://api.github.com/users/shirleiso28/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleiso28/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleiso",
      "id": 53271187,
      "node_id": "MDQ6VXNlcjUzMjcxMTg3",
      "avatar_url": "https://avatars.githubusercontent.com/u/53271187?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleiso",
      "html_url": "https://github.com/shirleiso",
      "followers_url": "https://api.github.com/users/shirleiso/followers",
      "following_url": "https://api.github.com/users/shirleiso/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleiso/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleiso/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleiso/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleiso/orgs",
      "repos_url": "https://api.github.com/users/shirleiso/repos",
      "events_url": "https://api.github.com/users/shirleiso/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleiso/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Shirleij",
      "id": 71672322,
      "node_id": "MDQ6VXNlcjcxNjcyMzIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/71672322?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Shirleij",
      "html_url": "https://github.com/Shirleij",
      "followers_url": "https://api.github.com/users/Shirleij/followers",
      "following_url": "https://api.github.com/users/Shirleij/following{/other_user}",
      "gists_url": "https://api.github.com/users/Shirleij/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Shirleij/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Shirleij/subscriptions",
      "organizations_url": "https://api.github.com/users/Shirleij/orgs",
      "repos_url": "https://api.github.com/users/Shirleij/repos",
      "events_url": "https://api.github.com/users/Shirleij/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Shirleij/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ShirleiMelo",
      "id": 78806478,
      "node_id": "MDQ6VXNlcjc4ODA2NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/78806478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ShirleiMelo",
      "html_url": "https://github.com/ShirleiMelo",
      "followers_url": "https://api.github.com/users/ShirleiMelo/followers",
      "following_url": "https://api.github.com/users/ShirleiMelo/following{/other_user}",
      "gists_url": "https://api.github.com/users/ShirleiMelo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ShirleiMelo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ShirleiMelo/subscriptions",
      "organizations_url": "https://api.github.com/users/ShirleiMelo/orgs",
      "repos_url": "https://api.github.com/users/ShirleiMelo/repos",
      "events_url": "https://api.github.com/users/ShirleiMelo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ShirleiMelo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleiveloso",
      "id": 76831427,
      "node_id": "MDQ6VXNlcjc2ODMxNDI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/76831427?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleiveloso",
      "html_url": "https://github.com/shirleiveloso",
      "followers_url": "https://api.github.com/users/shirleiveloso/followers",
      "following_url": "https://api.github.com/users/shirleiveloso/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleiveloso/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleiveloso/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleiveloso/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleiveloso/orgs",
      "repos_url": "https://api.github.com/users/shirleiveloso/repos",
      "events_url": "https://api.github.com/users/shirleiveloso/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleiveloso/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shirleibo",
      "id": 68895118,
      "node_id": "MDQ6VXNlcjY4ODk1MTE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/68895118?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shirleibo",
      "html_url": "https://github.com/shirleibo",
      "followers_url": "https://api.github.com/users/shirleibo/followers",
      "following_url": "https://api.github.com/users/shirleibo/following{/other_user}",
      "gists_url": "https://api.github.com/users/shirleibo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shirleibo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shirleibo/subscriptions",
      "organizations_url": "https://api.github.com/users/shirleibo/orgs",
      "repos_url": "https://api.github.com/users/shirleibo/repos",
      "events_url": "https://api.github.com/users/shirleibo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shirleibo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}



 """;